Ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('registration.backends.default.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('myapp.urls')),
    path('paypal/', include("paypal.standard.ipn.urls")),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.urls import path
from myapp.views import products,detail,cart_view,return_view,cancel_view,order,grocery,review,send_email,category
app_name='myapp'
urlpatterns = [
    path('',category,name='category'),
    path('products/<int:product_id>/<slug:slug>',products,name='products'),
    path('<int:product_id>/<slug:slug>',detail,name='detail'),
    path('cart/',cart_view, name='cart_view'),
    path('order/',order,name='order'),
    path('success/',return_view,name='return_view'),
    path('cancel/',cancel_view,name='cancel_view'),
    path('<int:product_id>/<slug:slug>/review/',review,name='review'),
    path('sendmail/',send_email,name='send_email'),
   ]

    

myapp/models.py
from django.db import models
from django .contrib.auth.models import User
class Category(models.Model):
    title=models.CharField(max_length=50)
    img=models.ImageField(upload_to='')
    slug=models.SlugField()
    def __str__(self):
        return self.title
class Product(models.Model):
    title=models.CharField(max_length=100)
    description=models.TextField()
    slug=models.SlugField()
    price=models.DecimalField(max_digits=10,decimal_places=2)
    img=models.ImageField(upload_to='')
    product_available=models.BooleanField(default=False)
    category = models.ForeignKey(Category,on_delete=models.CASCADE,default=1)
    def __str__(self):
        return self.title 
class Cart(models.Model):
    cart_id=models.CharField(max_length=100)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    quantity=models.IntegerField()
    timestamp=models.DateTimeField(auto_now=True)
    product=models.ForeignKey(Product,on_delete=models.PROTECT)
    def __str__(self):
        return self.product.title 
    def update_quantity(self,quantity):
        self.quantity+=quantity
        self.save()
    def total(self):
        return self.quantity*self.price
class Buy(models.Model):
    product=models.ForeignKey(Product,on_delete=models.PROTECT)
    quantity=models.IntegerField()
    price=models.DecimalField(max_digits=10,decimal_places=2)

    def __str__(self):
        return self.product.title+'_'+str(self.id)

class TimeStamp(models.Model):
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)
	user = models.ForeignKey(User,on_delete = models.CASCADE)

	class Meta:
		abstract = True

class Review(TimeStamp):
	post = models.ForeignKey(Product,on_delete = models.CASCADE)
	review = models.TextField()

	def __str__(self):
		return self.review

        

myapp/forms.py
from django import forms
from myapp.models import Review

class CartForm(forms.Form):
    quantity=forms.IntegerField(initial='1')
    product_id=forms.IntegerField(widget=forms.HiddenInput)

    def __init__(self,request,*args,**Kwargs):
       self.request=request
       super(CartForm,self).__init__(*args,**Kwargs)

class ReviewForm(forms.ModelForm):
	class Meta:
		model = Review
		fields = ['review']      

myapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from myapp.models import Product,Cart,Buy,Review,Category
from myapp.forms import CartForm,ReviewForm
from myapp.myapp import *
from django.urls import reverse
from django.shortcuts import render
from paypal.standard.forms import PayPalPaymentsForm
from django.core.mail import BadHeaderError, send_mail
from django.contrib.auth.decorators import login_required


# Create your views here.
def category(request):
    if 'q' in request.GET:
        q=request.GET['q']
        c=Category.objects.filter(title__icontains=q)
        print(c)
    else:
        c = Category.objects.all()
    context = {'c': c}
    return render(request, 'categories.html',context)
def products(request,product_id,slug):
    p=Product.objects.filter(category=product_id)
    if request.GET.get('q'):
        query=request.GET.get('q')
        p=Product.objects.filter(title__icontains=query)
    context={'p':p}
    return render(request,'index.html',context)
  
def detail(request,product_id,slug):
    d=Product.objects.get(id=product_id)
    reviews = Review.objects.filter(post_id = product_id)
    if request.method=="POST":
        f=CartForm(request,request.POST)
        if f.is_valid():
            request.form_data=f.cleaned_data
            add_to_cart(request)
            return redirect('myapp:cart_view')
    
    f=CartForm(request,initial={'product_id':product_id})
    context={'d':d,'f':f,'reviews':reviews}
    return render(request,'detail.html',context)
def cart_view(request):
    if request.method=="POST" and request.POST.get('delete')=='Delete':
        item_id=request.POST.get('item_id')
        cd=Cart.objects.get(id=item_id)
        cd.delete()
    c=get_cart(request)
    t=total_(request)
    co=item_count(request)
    context={'c':c,'t':t}
    return render(request,'cart.html',context)
@login_required
def order(request):
    # What you want the button to do.
    items=get_cart(request)
    for i in items:
        b=Buy(product_id=i.product_id,quantity=i.quantity,price=i.price)
        b.save()
    paypal_dict = {
        "business": "sb-gn7fj28540309@business.example.com",
        "amount": total_(request),
        "item_name": cart_id(request),
        "invoice": str(uuid.uuid4()),
        "notify_url": request.build_absolute_uri(reverse('paypal-ipn')),
        "return": request.build_absolute_uri(reverse('myapp:return_view')),
        "cancel_return": request.build_absolute_uri(reverse('myapp:cancel_view')),
        "custom": "premium_plan",  # Custom command to correlate to some function later (optional)
    }

    # Create the instance.
    form = PayPalPaymentsForm(initial=paypal_dict)
    context = {"form": form,"items":items,"total":total_(request)}
    return render(request, "order.html", context)
def return_view(request):
    return render(request,'transraction.html')
def cancel_view(request):
    return HttpResponse('Transaction Cancelled')
def grocery(request):
    return render(request,'grocery.html')
def review(request,product_id,slug):
    d=Product.objects.get(id=product_id)
    reviews = Review.objects.filter(post_id = product_id)
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.cleaned_data['review']
            c = Review(post_id = product_id,review = review,user = request.user)
            c.save()
            
    else:
        form = ReviewForm()

    return render(request, 'review.html', {'d':d,'form': form,'reviews':reviews})

def send_email(request):
    subject = request.POST.get("subject", "Hi Pushpa")
    message = request.POST.get("message", "OTP is 78742")
    from_email = request.POST.get("from_email", "velisilap@gmail.com")
    if subject and message and from_email:
        try:
            send_mail(subject, message, from_email, ["velisilap@gmail.com"])
        except BadHeaderError:
            return HttpResponse("Invalid header found.")
        return HttpResponseRedirect("Mail sent to Pushpa")
    else:
        # In reality we'd use a form class
        # to get proper validation errors.
        return HttpResponse("Make sure all fields are entered and valid.")

        

myapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charsett="UTF-8">
  <meta name="viewport" content="width=device-width,
  initial-scale=1.0">
  <title>Grocery</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
	<link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-light" style="background-color: greenyellow;">
 <i><a style="background-color: greenyellow" class="navbar-brand" href="http://127.0.0.1:8000/"><b>Grocery</b></a></i>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="http://127.0.0.1:8000/products/1/vegetables"><b>Vegetables</b><span class="sr-only">(current)</span></a>
      </li>
    </ul>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="http://127.0.0.1:8000/products/3/snacks"><b>Snacks</b><span class="sr-only">(current)</span></a>
          </li>
        </ul>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="http://127.0.0.1:8000/products/5/oilsandmasala"><b>Oil&Masala</b><span class="sr-only">(current)</span></a>
            </li>
    </ul>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="http://127.0.0.1:8000/products/2/personalcare"><b>Personal Care</b><span class="sr-only">(current)</span></a>
        </li>
    </ul>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="http://127.0.0.1:8000/products/4/foodgrains"><b>Food Grains</b><span class="sr-only">(current)</span></a>
        </li>
      </ul>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="http://127.0.0.1:8000/products/6/babycare"><b>Baby Care</b><span class="sr-only">(current)</span></a>
          </li>
        </ul> 
        <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" name="q" value="{{request.GET.q}}" placeholder="{{request.user}}" aria-label="Search">
      <a href="{% url 'myapp:cart_view' %}"class="btn btn-primary"> 🛒User Cart</a>
    </form>&nbsp;
    {% if not user.is_authenticated %}
    <a class="btn btn-primary" href="{% url 'auth_login' %}">Login</a>
    <a class="btn btn-primary" href="{% url 'registration_register' %}">Register</a>
    {% else %}
    <a class="btn btn-primary" href="{% url 'auth_logout' %}">Logout</a><br><br>
    
    {% endif %}
   
  </div>
</nav>

	{% block content %}
	
	{% endblock %}
</div>

</body>
</html>

myapp/templates/cart.html
{% extends 'base.html' %}
{% block content %}
<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Product</th>
        <th scope="col">Price</th>
        <th scope="col">Quantity</th>
        <th scope="col">Total Cost</th>

      </tr>
    </thead>
    <tbody>
    {% for i in c %}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{i.Product}}</td>
        <td>{{i.Price}}</td>
        <td>{{i.Quantity}}</td>
        <td>{{i.Total}}</td>
        <td>
        <form action="" method="post">
            {% csrf_token %}
            <input type="hidden" name="item_id" value="{{i.id}}">
            <input class="btn btn-danger" type="submit" name="delete" value="Delete">
        </form>
      </td>
      </tr>
      {% endfor %}
    </tbody>  
  </table><br>
  Total: ₹{{t}}<br>
  <br><br>
  <a class="btn btn-info" href="{% url 'myapp:order' %}">Order</a>
  &nbsp;&nbsp;&nbsp;
  <a class="btn btn-info" href="{% url 'myapp:category' %}">Back/Continue</a>
  <style>
    body{
      font-size: 16px;
    }
  </style>
  {% endblock %}

myapp/templates/categories.html
{% extends 'base.html' %}
{% block content %}
<center><h1 style="color:orangered;">GROCERY PRODUCTS</h1></center>
<img src="https://www.welfareeshopping.com/frontAssets/images/banner-4.jpg" width="100%" height="700">
<center><b><h1>Products By Category</h1></b></center>
<div class="w3-container">
    <div class="row">
        {% for i in c %}
        <div class="col-md-4 mb-4">
            <div class="card">
              <center><img src="{{ i.img.url }}" class="card-img-top img-fluid rounded" alt="{{ i.title }}" style="max-width: 200px; height: 210px; object-fit: cover;">
                <div class="card-body">
                    <h5 class="card-title">
                        <a href="{% url 'myapp:products' i.id i.slug %}">{{ i.title }}</a>
                    </h5>
                </div>
            </div>
        </div></center> 
        {% endfor %}
    </div><br></div>
    <div class="card primary card-expand-lg bg-success">
      <br> <center><h1>CONTACT US</h1></center>
      <h5><i class="material-icons">place:-</i><a href="https://www.google.com/maps/place/Parvathaneni+Brahmayya+Siddhartha+college+of+Arts+%26+Science/@16.5055349,80.6469164,17z/data=!4m15!1m8!3m7!1s0x3a35fab6cd09a89b:0xd33167f96ffe60b7!2sGJ4X%2B6Q9+PB+Siddhartha+College+Gym,+Mogalrajapuram,+Siddhartha+Nagar,+Benz+Circle,+Vijayawada,+Andhra+Pradesh+520010!3b1!8m2!3d16.5055298!4d80.6494913!16s%2Fg%2F1hhj1fh8g!3m5!1s0x3a35fab12587c72b:0x20aec0bac504143c!8m2!3d16.5050802!4d80.648373!16s%2Fg%2F1tzvtzmq?entry=ttu" class="text-dark">PARVATHANENI BRHAMAYYA SIDDHARTHA COLLEGE OF ARTS AND SCINCE</a></h5>
      <h5><i class="material-icons">local_phone:-</i>7794964155</h5>
      <h5><i class="material-icons">mail:-</i>velisilap@gmail.com</h5>
      <CENTER><h2>FOLLOW US</h2></CENTER>
      <h4> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="https://twitter.com/i/flow/login?redirect_after_login=%2FPBSiddharthaco2" class="text-dark"  style='font-size:24px'><i class="fa fa-twitter"></i></a>&nbsp;&nbsp;<a href="https://www.facebook.com/pbsiddharthaclg/" class="text-dark" style='font-size:24px'><i class="material-icons" class="text-dark">facebook</i></a>&nbsp;&nbsp;<a href="https://www.instagram.com/pbsiddharthacollege/" class="text-dark" style='font-size:24px'><i class="fa fa-instagram"></i></a>&nbsp;&nbsp;<a href="https://www.linkedin.com/school/parvathaneni-brahmayya-siddhartha-college-of-arts-&-science/?originalSubdomain=in" class="text-dark" style='font-size:24px'><i class="fa fa-linkedin-square"></i></a></h4>
    <br>
      <br>
    </div></div>

    {% endblock %}

myapp/templates/detail.html
{% extends 'base.html' %}
{% block content %}
<style>
    body{
        font-size: 20px;
    }
</style>    
<div class="container">
<div class="row">
<div class="col-md-6">
   <h2> {{d.title}}</h2><br> 
        {{d.description}}<br><br>
       <b> ₹{{d.price}}</b><br>
</div>
        <div class="col-md-6">
       <br> <img src="{{d.img.url}}" widt="400" height="500" >
        </div>
    </div>

<form action="{% url 'myapp:detail' d.id d.slug%}" method="post">
    {% csrf_token %}
    {{ f }}
    <input type="submit" value="Add to Cart">
</form>
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
   
	</form>

	</div>

</div>
	<br><br><br>
	<h6>Reviews:</h6>
    
    {% for i in reviews %}

    {{forloop.counter}} - {{i.review}} <br>
    at {{i.created_at}} by {{i.user}} <br></center>

    {% endfor %}

</div>


{% endblock %}

myapp/templates/index.html
{% extends 'base.html' %}
{% block content %}
<center><h1 style="color:orangered;">GROCERY PRODUCTS</h1></center>
<div class="container">
  <div class="row">
    <div class="row">
      {% for i in p %}
      <div class="col-md-4 mb-4">
        <div class="card">
              <center><img src="{{i.img.url}}" width="150" height="150"></center><br>
              <div class="card-body">
                {% if i.product_available is True %}
                <center><h5 class="card-title"><a href="{% url 'myapp:detail' i.id i.slug %}"><b>{{i.title}}</b></a><br></h5>
                ⟨₹⟩{{i.price}}</center>
                <br><br>
                {% else %}   
                <b>Out Of Stock</b>
                {% endif %}
              </div>
            </div> 
          </div>
  
      {% endfor %} <br><br> 
        </div>
       
  </div>
  
  {% endblock %}
</div>

myapp/templates/order.html
{% extends 'base.html' %}
{% block content %}
<style>
    body{
        font-size: 20px;
    }
</style>
<b><h3>Cart</h3></b>
{% for i in items %}
{{i.product}}<br>
{% endfor %}
Pay: {{total}}
<h1>Show me the money!</h1>
<!-- writes out the form tag automatically -->
{{ form.render }}
{% endblock %}
 

myapp/templates/review.html
{% extends 'base.html' %}
{% block content %}
<center><style>
    body{
        font-size: 20px;
    }
</style>
<div class="row">
    <div class="col-md-6">
    <b>{{d.title}}</b><br>
    {{d.description}}<br>
    {{d.price}}<br>
    </div>
    <div class="col-md-6">
        <img src="{{d.img.url}}" widt=300 height="300">
    </div>

</div> 

myapp/templates/transraction.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center><br><br><br><br>
    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7fLGbTFZKIDyOeXJFQ3C16nwyt-qlL4iKyA&usqp=CAU" width="70" height="70">
    <h1>Order Placed</h1>
    </center>
</body>
</html>